### ISSUE TITLE
Installation/Tutorial Issues

### ISSUE THREAD

**Issue by rx2k** [aehrc/redmatch#32]
Hello,

i've had a few problems following the installation tutorial.
First problem: Dead Link for redcap dictionary (FIXED: can be found manually)
Secound problem: Dictonary has doubles in it (FIXED: you have to rename a few variables yourself before uploading)
Third (UNFIXED) problem: Error during 
> maven clean verify :

(---------- SNIPPLET -------------)
[INFO] Building Redmatch UI 1.3.4                                         [2/3]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ ui ---
[INFO]
[INFO] --- exec-maven-plugin:3.0.0:exec (exec-yarn-install) @ ui ---
yarn install v1.22.10
warning ../package.json: No license field
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.99s.
[INFO]
[INFO] --- exec-maven-plugin:3.0.0:exec (exec-yarn-antlr4ts) @ ui ---
yarn run v1.22.10
warning ../package.json: No license field
$ antlr4ts -visitor src/grammar/au/csiro/redmatch/grammar/RedmatchLexer.g4 src/grammar/au/csiro/redmatch/grammar/RedmatchGrammar.g4
error(7):  cannot find or open file: src/grammar/au/csiro/redmatch/grammar/RedmatchLexer.g4
error(7):  cannot find or open file: src/grammar/au/csiro/redmatch/grammar/RedmatchGrammar.g4
child process exited with code  1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[ERROR] Command execution failed.
(---------- END OF SNIPPLET -------------)

It feels like some files in the repo have been moved incorrectly? Can someone help me with this issue?
Thanks in advance

Cheers Raphael

**Comment by ametke** [comment]
Thanks for reporting these issues. I've fixed them so hopefully you can build the project now. Feel free to reopen or add another issue if you run into any more problems.
