### ISSUE TITLE
Redmatch server failure

### ISSUE THREAD

**Issue by EthelEz** [aehrc/redmatch#41]
When I run mvn clean verify I get error from the server as stated below: I've tried to install

[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Redmatch
[INFO] Redmatch UI
[INFO] Redmatch Server
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Redmatch 1.3.4
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ redmatch ---
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-resources) @ redmatch ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Redmatch UI 1.3.4
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ ui ---
[INFO] 
[INFO] --- exec-maven-plugin:3.0.0:exec (exec-yarn-install) @ ui ---
yarn install v1.22.17
warning ../../../../../package.json: No license field
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.56s.
[INFO] 
[INFO] --- exec-maven-plugin:3.0.0:exec (exec-yarn-antlr4ts) @ ui ---
yarn run v1.22.17
warning ../../../../../package.json: No license field
$ antlr4ts -visitor src/grammar/au/csiro/redmatch/grammar/RedmatchLexer.g4 src/grammar/au/csiro/redmatch/grammar/RedmatchGrammar.g4
Generating file '/Users/ethelschinedu/fhirGenomics/fhirGenomeApp/redMatch/redmatch/ui/src/grammar/au/csiro/redmatch/grammar/RedmatchLexer.interp' for grammar 'src/grammar/au/csiro/redmatch/grammar/RedmatchLexer.g4'
Generating file '/Users/ethelschinedu/fhirGenomics/fhirGenomeApp/redMatch/redmatch/ui/src/grammar/au/csiro/redmatch/grammar/RedmatchLexer.ts' for grammar 'src/grammar/au/csiro/redmatch/grammar/RedmatchLexer.g4'
Generating file '/Users/ethelschinedu/fhirGenomics/fhirGenomeApp/redMatch/redmatch/ui/src/grammar/au/csiro/redmatch/grammar/RedmatchLexer.tokens' for grammar 'src/grammar/au/csiro/redmatch/grammar/RedmatchLexer.g4'
Generating file '/Users/ethelschinedu/fhirGenomics/fhirGenomeApp/redMatch/redmatch/ui/src/grammar/au/csiro/redmatch/grammar/RedmatchGrammar.interp' for grammar 'src/grammar/au/csiro/redmatch/grammar/RedmatchGrammar.g4'
Generating file '/Users/ethelschinedu/fhirGenomics/fhirGenomeApp/redMatch/redmatch/ui/src/grammar/au/csiro/redmatch/grammar/RedmatchGrammar.ts' for grammar 'src/grammar/au/csiro/redmatch/grammar/RedmatchGrammar.g4'
Generating file '/Users/ethelschinedu/fhirGenomics/fhirGenomeApp/redMatch/redmatch/ui/src/grammar/au/csiro/redmatch/grammar/RedmatchGrammarListener.ts' for grammar 'src/grammar/au/csiro/redmatch/grammar/RedmatchGrammar.g4'
Generating file '/Users/ethelschinedu/fhirGenomics/fhirGenomeApp/redMatch/redmatch/ui/src/grammar/au/csiro/redmatch/grammar/RedmatchGrammarVisitor.ts' for grammar 'src/grammar/au/csiro/redmatch/grammar/RedmatchGrammar.g4'
Generating file '/Users/ethelschinedu/fhirGenomics/fhirGenomeApp/redMatch/redmatch/ui/src/grammar/au/csiro/redmatch/grammar/RedmatchGrammar.tokens' for grammar 'src/grammar/au/csiro/redmatch/grammar/RedmatchGrammar.g4'
Done in 0.92s.
[INFO] 
[INFO] --- exec-maven-plugin:3.0.0:exec (exec-yarn-build) @ ui ---
yarn run v1.22.17
warning ../../../../../package.json: No license field
$ react-app-rewired build
Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run the following command: `npx browserslist --update-db`
Compiled with warnings.

src/api/RedmatchApi.ts
  Line 9:10:   'AxiosResponse' is defined but never used                               @typescript-eslint/no-unused-vars
  Line 10:10:  'IParameters' is defined but never used                                 @typescript-eslint/no-unused-vars
  Line 68:1:   Assign arrow function to a variable before exporting as module default  import/no-anonymous-default-export

src/components/CodeSearch.tsx
  Line 72:13:  'ServerResponse' is defined but never used  @typescript-eslint/no-unused-vars

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

File sizes after gzip:

  862.75 KB  build/static/js/2.a16a9a91.chunk.js
  73.6 KB    build/json.worker.js
  44.03 KB   build/editor.worker.js
  28.84 KB   build/static/js/3.0f82bb1b.chunk.js
  20.42 KB   build/static/js/main.a8940e43.chunk.js
  12.5 KB    build/static/css/2.92855bb5.chunk.css
  1.17 KB    build/static/js/runtime-main.2126936a.js
  278 B      build/static/css/main.6dea0f05.chunk.css

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  yarn global add serve
  serve -s build

Find out more about deployment here:

  https://cra.link/deployment

Done in 45.92s.
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-resources) @ ui ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/ethelschinedu/fhirGenomics/fhirGenomeApp/redMatch/redmatch/ui/server/src/main/antlr4
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Redmatch Server 1.3.4
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ server ---
[INFO] Deleting /Users/ethelschinedu/fhirGenomics/fhirGenomeApp/redMatch/redmatch/server/target
[INFO] 
[INFO] --- build-helper-maven-plugin:3.2.0:add-source (default) @ server ---
[INFO] Source directory: /Users/ethelschinedu/fhirGenomics/fhirGenomeApp/redMatch/redmatch/server/target/generated-sources/antlr4/java added.
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-resources) @ server ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/ethelschinedu/fhirGenomics/fhirGenomeApp/redMatch/redmatch/server/server/src/main/antlr4
[INFO] 
[INFO] --- antlr4-maven-plugin:4.8-1:antlr4 (antlr-java) @ server ---
[INFO] ANTLR 4: Processing source directory /Users/ethelschinedu/fhirGenomics/fhirGenomeApp/redMatch/redmatch/server/src/main/antlr4
[INFO] Processing grammar: au/csiro/redmatch/grammar/RedmatchLexer.g4
[INFO] Processing grammar: au/csiro/redmatch/grammar/RedmatchGrammar.g4
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Redmatch ........................................... SUCCESS [  0.278 s]
[INFO] Redmatch UI ........................................ SUCCESS [ 48.213 s]
[INFO] Redmatch Server .................................... FAILURE [  1.338 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 50.211 s
[INFO] Finished at: 2021-11-17T16:58:27+00:00
[INFO] Final Memory: 33M/381M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:license-maven-plugin:2.0.0:add-third-party (add-third-party) on project server: The plugin org.codehaus.mojo:license-maven-plugin:2.0.0 requires Maven version 3.5.4 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginIncompatibleException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :server

I noticed some issues with `yarn add -W caniuse-lite` and have tried to resolve it and getting 

error An unexpected error occurred: "https://registry.yarnpkg.com/hl7.fhir.us.mcode: Not found".

Please, is there any help you can offer?

**Comment by ametke** [comment]
Hi. The stack trace you sent seems to indicate that the problem is your version of Maven:

```
[ERROR] Failed to execute goal org.codehaus.mojo:license-maven-plugin:2.0.0:add-third-party (add-third-party) on project server: The plugin org.codehaus.mojo:license-maven-plugin:2.0.0 requires Maven version 3.5.4 -> [Help 1]
```

Try upgrading Maven to a version >= 3.5.4 and see if that helps.

**Comment by EthelEz** [comment]
Hello ametke,

Thank you for your quick response.

I have upgraded maven to 3.5.4, yet the issues persist. At the moment I have maven 3.8.3 and yet having issues with the Browserslist:

" Browserslist: caniuse-lite is outdated. Please run the following command: `npx browserslist --update-db` "

I have updated the Browserslist, installed and reinstalled it with npm, yet the server doesn't run. 

I am just stuck, still need help please!

**Comment by ametke** [comment]
Hi EthelEz,

I have just released a new version of Redmatch that is now a combination of a command line interface and a Visual Studio Code extension. I suggest you try the new version. I think the user experience will be much better. I will not be supporting v1 moving forward.

**Comment by EthelEz** [comment]
Hello ametke,

Thank you for the update. 
I am going through the updated version. I will keep you posted on any issues I might likely encounter.
