### ISSUE TITLE
Right-clicking on the tutorial.rdm file, there's no "Transform this file" command

### ISSUE THREAD

**Issue by myerou02ucy** [aehrc/redmatch#54]
Hello,

I have installed the VS Code extension from the marketplace, and it seems to be installed successfully. But there's no color coding for *.rdm files and no option "Transform this file" when right-clicking on *.rdm files (in File Exporter or VS Code).

Any help would be appreciated. 

Thank you in advance.

**Comment by johngrimes** [comment]
Hi @myerou02ucy,

Apologies for the late reply.

You need to click on the contents of the file itself to find the "Transform this file" menu option.

I think the documentation needs updating - I will make this change.

**Comment by myerou02ucy** [comment]
Thank you for your reply!
